services:
  - type: web
    name: chasseauxoeuf
    env: php
    buildCommand: |
      composer install --no-dev
      mkdir -p build
      mkdir -p build/data
      cp -r *.php *.js *.css img build/
      chmod -R 755 build
      chmod -R 777 build/data
    startCommand: |
      cd build && php -d display_errors=1 -d error_reporting=E_ALL -S 0.0.0.0:$PORT
    publishDirectory: build
    healthCheckPath: /
    envVars:
      - key: SUPABASE_URL
        value: https://nbqssxhroavedcnjloys.supabase.co
        sync: false
      - key: SUPABASE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5icXNzeGhyb2F2ZWRjbmpsb3lzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzIyODgzNzcsImV4cCI6MjA0Nzg2NDM3N30.nlYK3l6l4wDqeWEEMknBSsBzlt0bLlFLGkFkbaluZj0
        sync: false
      - key: NODE_VERSION
        value: 16.20.0
